### PR TITLE
Set up `scikit-build` for packaging and distribution

### PR DESCRIPTION
**Pull request by karlhigley**
Trying to get this set up to work on macOS at least, and hoping we can use [`dockcross`](https://github.com/dockcross/dockcross) to build wheels for other platforms.

### CODE REVIEW

**Comment by youben11** [comment]
Why do we need scikit-build to use it with dockross? if the docker images are ready then using `pip` and `auditwheel` should be enough I think to get the wheels ready to be pushed

**Comment by karlhigley** [comment]
It has [good support](https://scikit-build.readthedocs.io/en/latest/generators.html) for a variety of compiler toolchains without having to write much code in `setup.py`.

**Comment by karlhigley** [comment]
(And should work with `manylinux` too.)

**Comment by youben11** [comment]
Thanks a lot @karlhigley :heart: but we preferred to keep the same build tools and automate the publishing on release for Linux #27 and MacOS #25 (Windows is on its way) via github actions.

**Comment by karlhigley** [comment]
Excellent! Let's close this then.

**Pull request closed without merging**
